# These are supported funding model platforms

# GitHub Sponsors - uncomment and add your GitHub username if you set up GitHub Sponsors
github: rodriguescarson

# Patreon - uncomment and add your Patreon username
patreon: rodriguescarson

# Ko-fi - uncomment and add your Ko-fi username
# ko_fi: rodriguescarson

# Buy Me a Coffee - uncomment and add your Buy Me a Coffee username
buy_me_a_coffee: rodriguescarson

# Custom URLs - add your personal website or other donation links
custom: ['https://carsonrodrigues.com']

# Other options (uncomment if you use them):
# open_collective: # Replace with a single Open Collective username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
# thanks_dev: # Replace with a single thanks.dev username
